strict: false
index: false
testmode: false
obo_assumption: true
batch: true
safe_label: loose
batch_size: 100000000
obo_assumption_overwrite_defaults:
  - iris:
      - "http://purl.obolibrary.org/obo/IAO_0000115"
      - "http://www.geneontology.org/formats/oboInOwl#hasExactSynonym"
property_mapping:
  - iris:
      - "http://purl.obolibrary.org/obo/so#part_of"
      - "http://purl.obolibrary.org/obo/BFO_0000050"
    id: part_of
  - iris:
      - "http://purl.obolibrary.org/obo/fbbt#has_quality"
      - "http://purl.obolibrary.org/obo/so#has_quality"
      - "http://purl.obolibrary.org/obo/RO_0000086"
    id: has_quality
  - iris:
      - "http://www.w3.org/2002/07/owl#deprecated"
    id: deprecated
    datatype: "Boolean"
neo_node_labelling:
  - label:  Neuron_adult
    expressions:     
      - VFB:000002     
      - RO:0000060 some VFB:000001